### PR TITLE
Fix: qiradb trace file & update to latest travis platform, ida build script hardcoded paths, pydot fix and some clean-ups

### PR DESCRIPTION
**Pull request by Maroc-OS**
Fix: Warnings on qiradb trace file & ida build script shouldn't be hardcoded, use something similar to export IDA_SDK=~/idasdk68 && export IDA_DIR=~/ida-6.8

### CODE REVIEW

**Comment by Maroc-OS** [comment]
built successfully with **gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2).**

**Before Patch :**
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c qiradb/Trace.cpp -o build/temp.linux-x86_64-2.7/qiradb/Trace.o
    
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    
    qiradb/Trace.cpp: In member function ‘bool Trace::remap_backing(uint64_t)’:
    
    qiradb/Trace.cpp:108:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    
         if (fs < new_size) {
    
                ^
    
    qiradb/Trace.cpp:109:37: error: expected ‘)’ before ‘PRIu64’
    
           printf("WARNING: requested %" PRIu64 " bytes, but only %llx are in the file...waiting\n", new_size, fs);
    
                                         ^
    
    qiradb/Trace.cpp:109:109: warning: spurious trailing ‘%’ in format [-Wformat=]
    
           printf("WARNING: requested %" PRIu64 " bytes, but only %llx are in the file...waiting\n", new_size, fs);
    
                                                                                                                 ^
    
    qiradb/Trace.cpp:109:109: warning: too many arguments for format [-Wformat-extra-args]
    
    qiradb/Trace.cpp: In member function ‘void Trace::process()’:
    
    qiradb/Trace.cpp:195:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    
         if (type == 'W' && c->address < (register_size_ * register_count_)) {
    
                                       ^
    
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**After Patch :**
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c qiradb/Trace.cpp -o build/temp.linux-x86_64-2.7/qiradb/Trace.o

    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    qiradb/Trace.cpp: In member function ‘bool Trace::remap_backing(uint64_t)’:
    qiradb/Trace.cpp:109:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (fs < new_size) {
                ^
    qiradb/Trace.cpp: In member function ‘void Trace::process()’:
    qiradb/Trace.cpp:196:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (type == 'W' && c->address < (register_size_ * register_count_)) {
                                       ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c qiradb/_qiradb.cpp -o build/temp.linux-x86_64-2.7/qiradb/_qiradb.o

    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/qiradb/Trace.o build/temp.linux-x86_64-2.7/qiradb/_qiradb.o -o build/lib.linux-x86_64-2.7/qiradb/_qiradb.so
Successfully installed qiradb-1.2
`

**Comment by Maroc-OS** [comment]
Tested with llvm/clang it works like a charm too. 

export CC=clang
export CXX=clang++

**Ubuntu clang version 3.6.2-1 (tags/RELEASE_362/final) (based on LLVM 3.6.2)**

**Comment by nedwill** [comment]
Did you mean to make another commit here? It looks like the build failed in Travis.

**Comment by Maroc-OS** [comment]
Okay it seems great now :) feel free to tell me what you think. the build now use new travis platform due to changes to .travis.yml

**Comment by Maroc-OS** [comment]
for the file  **ida/bin/qira_ida66_linux.plx** it's built using latest sdk 6.8 i cannot build for 64bit version i don't have the library for it

**Comment by nedwill** [comment]
Thanks for the cleanup you've done so far! Can you be me specific about the issue with the IDA SDK? It should have been built against 6.6. I thought building with version 6.8 / SDK 6.6 would allow people on 6.6 to use it but I guess it makes sense that that doesn't work.

**Comment by Maroc-OS** [comment]
Hey :) am not sure what do you mean, but if i really understand building with latest sdk will not work for olders but sometimes it works if the headers used are not changed. and i sent the pull request without checking that the ida plugin is there "i forgot i have already built it before sending the PR" you can change it by the old one if you want.

Thank btw.

**Comment by geohot** [comment]
Thanks for the fixes! Merging in.

Could build the IDA plugin with both 6.6 and 6.8, though I though they were forward compatible.

**Pull request merged**
