### PR TITLE
Adds a BIL Concrete Executor

### PR DESCRIPTION
**Pull request by tim-becker**
This PR adds a concrete executor for the BAP IL. As of now, it is not used anywhere, but it should hopefully be integrated into the tests soon.

### CODE REVIEW

**Comment by geohot** [comment]
A few things, it's not clear this code should be in QIRA and not BAP. That said, QIRA is fine if you think it is, but move it out of middleware.

**Comment by tim-becker** [comment]
We were initially planning on leaving this out of QIRA, but after seeing it identify bugs in QIRA, it seems that it could be useful to build some test cases around it. Additionally, we will soon be extending it to a concolic executor, which will be useful for QIRA.

As long as you're in agreement, where would be a reasonable place to put this?

**Comment by geohot** [comment]
I think of it more like pin or QEMU, let's move pin and qemu into a folder called tracers, then put this in tracers/<whatever you want to call it>

**Comment by geohot** [comment]
Done. It's super cool that BAP matches byte for byte on this stuff. Add to whatever you want to call it under tracers/

Also, can we add this to the regression testing suite?

**Comment by tim-becker** [comment]
Moved

**Pull request merged**
