### PR TITLE
Avoiding conditional directives that break statements

### PR DESCRIPTION
**Pull request by RomeroMalaquias**

### CODE REVIEW

**Comment by nedwill** [comment]
I see what you're referring to with the readability of that conditional directive, though I think it could be made even more readable my removing the `#if` altogether and putting the `HOST_LONG_BITS > TARGET_VIRT_ADDR_SPACE_BITS` directly into the conditional. Then the compiler can just constant fold it.

I assume you had Linux kernel style in mind here, and they seem to advocate this approach:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n906

**Comment by nedwill** [comment]
Oh, also that file is under `extra/`, meaning it is deprecated. Please see `tracers/qemu.patch` for our current qemu patch.

**Comment by geohot** [comment]
@nedwill I like that link, nice citation.

**Comment by RomeroMalaquias** [comment]
@nedwill, yep, is the Linux kernel style. Thanks for comments.
One question, which style do you prefer?

**Comment by nedwill** [comment]
I think removing the `#if` is preferable.

**Comment by sanshiromx** [comment]
@geohot bro, sorry to catch you here, is there any way to invite you to a conference event in Mexico? :) we have tequila and a lot of gorditas :D

**Comment by nedwill** [comment]
@sanshiromx Please correspond with him for this sort of thing over email.

**Comment by sanshiromx** [comment]
T-T i don't have your email @geohot, don't be bad @nedwill

**Pull request closed without merging**
