### PR TITLE
Change ints to size_t's to allow for big traces

### PR DESCRIPTION
**Pull request by tylerni7**
sometimes a uint32_t just doesn't cut it, you know?

### CODE REVIEW

**Comment by geohot** [comment]
Huh, why is travis broken. I don't this this broke it.

**Comment by tylerni7** [comment]
I don't know.. but it seems pretty sad; happy to wait for Travis to be happy again before merging

**Comment by nedwill** [comment]
I see

```
Traceback (most recent call last):
  File "/home/travis/build/BinaryAnalysisPlatform/qira/middleware/qira.py", line 14, in <module>
    import qira_webserver
  File "/home/travis/build/BinaryAnalysisPlatform/qira/middleware/qira_webserver.py", line 48, in <module>
    import gevent
ImportError: No module named gevent
```
in the Travis log. Maybe gevent got updated and broke us?

**Comment by nedwill** [comment]
@tylerni7 It seems it was the `gevent` thing. Someone made a pull request to fix it, so do you mind merging from master? Then this should be working.

**Comment by tylerni7** [comment]
Yay, it passed. Someone else want to merge it so I'm not merging my own patch?

**Pull request merged**
