### PR TITLE
User Interface Update

### PR DESCRIPTION
**Pull request by cganas**
I have been working on an interface overhaul for qira. It is not "merging into master" ready but I think it is ready enough for feedback and suggestions.

Note that this screenshot is from a 4k monitor.
qira_ui

The ui is built using the [wcDocker](https://github.com/WebCabin/wcDocker) library which allows us to abstract away the user interface elements of qira into panels, tabs, and other good things. All of the elements are re-sizable, detachable, and movable within the interface. In theory, you can also dynamically add tabs (which we don't get for free because of how qira's ui works), save and restore user layouts, and collapse panels into a dock.

There is still a lot to add and fix but I think these changes are taking a step in the right direction. qira deserves a premium desktop quality user interface.

There are some known issues. The biggest by far being the hardcoded values for memory, instructions, etc.
- Need to minify the dependencies for jquery context menu.
- Can not dynamically add panels because of how the interface is updated ( we should use classes instead of ids for elements). Would need to also resend the "autoruns" with the current state onAdd.
- Hardcoded number of things, e.g. instructions, memory have been adjusted but really need to adapt to the size of their container to provide a seamless experience.
- Memory/data panel should find some way to take advantage of the extra width. Also if you extend the memory panel past its maximal height (based on the hardcoded value) the spacing between lines increases in a distracting way. This should be fixed for free if we can remove the hardcoded values from the interface.
- Memory view has awkward scrollbar issues when using the mouse wheel. This would be solved if we can remove the hardcoded values.
- Should find a better way to keep the controls and registers+strace on top of the instruction trace without z-index. (Covers up the first few instructions of the trace)

General notes.
- We could have the memory/data panel dynamically added. Similar to how the current ui only shows it if you have selected a data region.
- As @tim-becker pointed out, it would be great if we could have multiple, independent data views. This would require the data view to become "smarter" in that we would only want one of them to sync when an address is clicked.
- I'd like to add a navbar with the indirect purpose of exposing a settings menu amongst other things you would expect from a desktop ui. Notably, with wcDocker, we have the ability to export and restore layouts.

### CODE REVIEW

**Comment by geohot** [comment]
OMG this makes me so happy!!!

**Comment by dbrumley** [comment]
Looks cool.  Does this affect how many elements can be drawn on screen as part of CFG's?  That is currently a problem; some functions CFG's push layout engines...even dot...over the deep end.

**Comment by cganas** [comment]
No, it does not. Actually the update inherits mostly all of the issues with master's current interface.

My goal with this initial mvp was to try to flesh out the kind of design that I found myself wanting for qira.

It did however give me a lot of insight into the relationship between qira's front and back end and areas we could improve moving forward. It would be great to compile a list of enhancements and tweaks once we iron out any fundamental issues with this initial draft.

**Comment by cganas** [comment]
I mentioned to @nedwill that we should design an interface element similar to IDA's Function Window to display a summative list of our function analysis. He mentioned that the information is already available, just not accessible from the current ui.

ida_func

We could have it highlight/sync to the clnum and serve as convenient lookup table. We already have the ability to rename data and other goodies.

**Comment by geohot** [comment]
Merge blocking comments:
* Those scrollbars everywhere are super annoying, fixing the hardcodeds are top priority to merge this
* There's a regression in the memory panel with the width changing as you scroll in addresses vs bytes

Smaller comments:
* When I x out a window I can't get it back without a refresh, either fix this or remove the x
* Can't resize the timeline size.
* Love the function window idea

Unrelated to this commit comments:
* The flat window has UI glitching bugs unrelated to this commit, but they should be fixed
* The oversized control graphs are not a UI problem. I'd just add an if to not draw if it's too big like IDA.
* Is the dot blocking? If so, fix this.

**Comment by geohot** [comment]
Also, the x's look weird on my computer, Windows 8.1 latest Chrome.

image

**Comment by dbrumley** [comment]
I mentioned this to others, but as an FYI:
$ bap-objdump --phoenix /tmp/foo <exe>
will output all cfg's for functions <exe> in /tmp/foo.

You can combine the above with --use-ida to have ida+byteweight, and --use-ida --no-byteweight to have just ida (default is just byteweight).

**Comment by dbrumley** [comment]
Oh, also you want --demangle

**Pull request merged**
