### PR TITLE
Fix install on arch (and python2 systems)

### PR DESCRIPTION
**Pull request by xtrm0**
Install wasn't working on arch.
With this patch it works again.

### CODE REVIEW

**Comment by nedwill** [comment]
My system (OS X) has `pip2` but not `virtualenv2`.

**Comment by xtrm0** [comment]
Going to fix that now

**Comment by xtrm0** [comment]
I think it is ok now

**Comment by nedwill** [comment]
On the `pacman` line where you install `python2-virtualenv`, does this install `virtualenv2`? Perhaps the `virtualenv` check should come after it's potentially installed.

**Comment by xtrm0** [comment]
nedwill I made the virtualenv checks to mimic the pip2 checks. Going to fix now

**Comment by xtrm0** [comment]
(done)

**Comment by nedwill** [comment]
This looks good. I'll trust you on the `qemu_build.sh` changes too since it works in Travis. Thanks!

**Pull request merged**
