### PR TITLE
Better way to filter library addresses

### PR DESCRIPTION
**Pull request by tim-becker**
This introduces a new way to filter library addresses which works by storing a

```
struct librarymap {
  struct librarymap *next;
  abi_ulong begin;
  abi_ulong end;
  const char *name;
};
```

for each library loaded at load-time and run-time. This achieves a few things:

* No more hardcoded PC comparisons, so library filtering works regardless of where they are loaded (yay MIPS support).
* Binaries with PIE can now be correctly traced without `--trace-libraries`

The one clear downside is that this considers anything that is mmap()d from a file descriptor to be a library. If this is often incorrect, we can try @nedwill's suggestion to only add the libraries specified in the ELF to the librarymap. This, however, won't catch any libraries that are loaded manually with `dlopen`.

Oh, and this also adds syscall detection on MIPS, so we get the correct register values afterwards.

### CODE REVIEW

**Comment by geohot** [comment]
Can you merge the two QEMU patches into one? (also, if you feel like it, upgrade to QEMU 2.4.0)

**Comment by nedwill** [comment]
I tested this on a PIE binary and it appears to work. Going based off `mmap` calls seems sufficient for now.

**Comment by tim-becker** [comment]
I merged the two into one patch, but updating to qemu 2.4 was causing headaches, so I gave up for tonight.

**Comment by geohot** [comment]
Oh, if the update is hard don't bother. Will test and merge when I get home.

**Comment by geohot** [comment]
Merged, but you actually have to delete the QEMU directory to force the new patches to be installed...long tern we should fix this.

**Pull request merged**
