### PR TITLE
Firefox support

### PR DESCRIPTION
**Pull request by Namalee**
Avoid the unwanted behavior of firefox with the shortcuts of qira

### CODE REVIEW

**Comment by geohot** [comment]
Thanks :)

**Comment by JohnLamb87** [comment]
@geohot Were you the hacker that cracked the 5C for the Fed?

**Comment by yeuchimse** [comment]
It seems that this fix also prevents you from editing any textbox (clnum, forknum...).

**Comment by Namalee** [comment]
Working to fix that. Will do a pull request soon (today probably).

**Pull request merged**
