### PR TITLE
Redefine REGS from tuple to list to allow assignement for dynamic types to fix endianess etc...

### PR DESCRIPTION
**Pull request by Maroc-OS**
Redefine REGS from tuple to list to allow assignment for dynamic types to fix endianess etc...

Remove IDA hardcoded version from qira plugins
Update PIP to latest version instead of 6.x.x
Add url and description to Qiradb package
Fix for #147 
Fix compiler warnings issue #145 
And maybe an incomplete fix for issue #92 

@geohot @nedwill

### CODE REVIEW

**Comment by Maroc-OS** [comment]
Fix for #147

**Comment by nedwill** [comment]
It looks like we can refactor the MIPS regs to be one list, and we update the endianness in the loader

**Comment by Maroc-OS** [comment]
yep :) this will allow us to pass anything to regs after the import so MIPS/MIPSEL can be done too.

```
 # mips
arch.MIPSREGS[2] = True
arch.MIPSREGS[3] = "mips"
```

```
 # mipsel
arch.MIPSREGS[2] = False
arch.MIPSREGS[3] = "mipsel
```

this is the result

**Comment by Maroc-OS** [comment]
One line is better then two, this is a test code : 

```
          arch.MIPSREGS[2:-1] = (True, "mips")
          print arch.MIPSREGS
```

**Comment by geohot** [comment]
LGTM

**Comment by Maroc-OS** [comment]
Good :) what LGTM means btw :P

**Comment by nedwill** [comment]
@Maroc-OS "Looks good to me."

**Pull request merged**
