### PR TITLE
Add support for little endian mips

### PR DESCRIPTION
**Pull request by tim-becker**
This adds support for mipsel binaries. Unfortunately, `fetchlibs.sh` still doesn't pull any mips libraries.

### CODE REVIEW

**Comment by nedwill** [comment]
This seems pretty good, but we should try to think of a nice way of packaging the mipsel libs. (We stole debian's libc for this during the CTF.) If people won't fiddle with BAP they're definitely not going to track down and manually unpack a deb.

**Comment by nedwill** [comment]
Works for me on `irkd` from defcon.

**Comment by tim-becker** [comment]
It's not just mipsel, even big endian libs aren't available that way.
I have something working that manually downloads and unpacks the debs, but it's not the cleanest solution. I can push that change if we want it to be part of this merge.

**Comment by tim-becker** [comment]
Also, all libraries are being traced on mips right now, because the load addresses aren't filtered by [the qemu patch](https://github.com/BinaryAnalysisPlatform/qira/blob/master/tracers/qemu.patch#L665).

**Comment by nedwill** [comment]
Yeah we need to do that qemu patch properly. And I'll leave it geohot for his opinion on the libraries thing. Probably not a huge deal but hopefully we can get something slightly cleaner than manually downloading a deb.

**Comment by nedwill** [comment]
Ah, I have a version that works on Debian. Give me a minute to clean up a bit then I'll merge this.

**Pull request merged**
