### PR TITLE
Very basic Mach-O Arm initial detection support

### PR DESCRIPTION
**Pull request by Maroc-OS**
Okay this is a very basic commit to allow better Mach-O detection plus ARM initial detection support.

Now more big/little endian , ARM and Pack200 compressed mach-o files can be detected.

it's a really basic PR.

This PR has some things referenced @ #143 

@geohot @nedwill

### CODE REVIEW

**Comment by Maroc-OS** [comment]
BTW i don't have a mac or idevice to test and to make more clean codes, so i did not tried to deal with pin.

maybe next will send a PR to deal with the fat binaries as i imagine it: so the idea is to extract or convert to 32bit on the fly and select 32bit arch on the target.

**Comment by Maroc-OS** [comment]
@nedwill @geohot anyone can check this RP?

**Comment by nedwill** [comment]
I can check tomorrow morning if geohot doesn't make do so in the meantime. I have a deadline at midnight here; I appreciate your patience.

**Comment by Maroc-OS** [comment]
of course :] tyt i hope am providing some little help here.

Tnx btw.

**Comment by Maroc-OS** [comment]
all thos tested on a linux machine so a simple output is :

```
root@mail:~/qira# qira ../ios_bins/my_bin
*** program is /home/xxxxxxxx/ios_bins/my_bin with hash 244ae49e6187ad8fc78bf842dc597414e02863ca
*** loader error: non-ELF detected
**** Mach-O binary detected
**** Mach-O ARM architecture detected
Running a Mach-O binary requires PIN support. See tracers/pin_build.sh
root@mail:~/qira#
```

**Comment by Maroc-OS** [comment]
travic-ci has a problem someone can restart the build on it?

**Comment by Maroc-OS** [comment]
I have a very last commit here to finish this initial support but i need a single arch 64bit arm file to test with.

**Comment by Maroc-OS** [comment]
@nedwill @geohot What this PR do now is checking the Mach-O binaries for all formats FAT, Normal or Pack200 compressed files, in both endianess little/big, it's detecting ARM/Aarch64 and raise NotImplementedError if the target is an ARM32/64 or FAT Pack200 compressed file, else! it continue as normal.

List of CPU TYPE/SUBTYPE processed.

```
    # 12       : CPU_TYPE_ARM
    # 0  : CPU_SUBTYPE_ARM_ALL
    # 5  : CPU_SUBTYPE_ARM_V4T
    # 6  : CPU_SUBTYPE_ARM_V6
    # 7  : CPU_SUBTYPE_ARM_V5TEJ
    # 8  : CPU_SUBTYPE_ARM_XSCALE
    # 9  : CPU_SUBTYPE_ARM_V7
    # 10 : CPU_SUBTYPE_ARM_V7F
    # 11 : CPU_SUBTYPE_ARM_V7S
    # 12 : CPU_SUBTYPE_ARM_V7K
    # 14 : CPU_SUBTYPE_ARM_V6M
    # 15 : CPU_SUBTYPE_ARM_V7M
    # 16 : CPU_SUBTYPE_ARM_V7EM

    # 16777228 : CPU_TYPE_ARM64
    # 0  : CPU_SUBTYPE_ARM64_ALL
```

For normal Mach-O binaries i still not yet added a correct way to deal with ARM 64bit cause i don't have any pure 64bit binary to check it's header. but in general it's working by only checking the 64bit magic.

**Comment by nedwill** [comment]
I'm going to review the changes now, thanks for bearing with me.

**Comment by Maroc-OS** [comment]
Take your time :)

**Comment by nedwill** [comment]
The code itself looks good, I'll try my best to actually test this locally since I have a Mac.

I'm using clang version `Apple LLVM version 7.0.2 (clang-700.1.81)` to make a couple test files since you noted you don't have a Mac. I put them under `tests_manual` if you're interested.

**Comment by Maroc-OS** [comment]
That would be great, feel free to note anything that looks strange to you.

Thank you.

**Comment by nedwill** [comment]
Ok those x86 ones seem to work. I'll try to cross compile for ARM, I see those were the ones you were missing.

**Comment by nedwill** [comment]
Yeah, it seems the iPhone cross-compiling stuff is kind of neutered on my installation for some reason, and I can't find a 64-bit only Mach-O binary myself. I'm preparing some comments on the code itself, thanks for testing it out on the binaries you did have.

**Comment by nedwill** [comment]
Please relabel "ARM" to "arm" and "Aarch64" -> "aarch64" at least internally, to be consistent with `arch.py`.

The bodies of the following elif statements:
```
elif progdat[0x0:0x04] == MACHO_FAT_MAGIC:
elif progdat[0x0:0x04] == MACHO_FAT_CIGAM:
```
are the same so you can refactor to simply:
```
elif progdat[0x0:0x04] in (MACHO_FAT_MAGIC, MACHO_FAT_CIGAM):
```

You can remove the comments describing CPU types / subtypes; the code should document itself.

In the future, you might find `struct.pack` useful to avoid typos like the one you had in commit 6c2a3be8cda29f96e679cc5261e15eaf688bd7f1.
It's designed for these kinds of use cases moving between ints and packed strings. I realize the original code didn't make use of this, but it did just occur to me. :)

On another note there are magic values everywhere (in the original code). This code needs some serious refactoring at some point.

**Comment by nedwill** [comment]
Thanks for the fixes; this looks good.

**Pull request merged**
