### PR TITLE
Make static non-blocking, support runtime error checks in tester

### PR DESCRIPTION
**Pull request by nedwill**
Before, QIRA would not respond until it finished the static analysis. For large programs, this could take minutes, which was unacceptable. In this pull request, I address this problem by running the analysis in a thread, just like the dynamic analysis is currently done. I've also fixed a bug in which the instruction view and the static view (when enabled) would fail to display properly when the dynamic analysis took a long time to complete, never setting trace.maxclnum.

In summary, these changes allow a user to jump right into the trace, with the static view on the right updating to display functions as they are identified. Before making these changes, I checked bap-objdump and IDA against QIRA's static performance. It was apparent to me that these tools can take a significant amount of time to finish autoanalysis as well, but with IDA the user interface is immediately available and so the user experience is vastly improved. We're much more IDA-like now in this regard.

We now also support checking for runtime errors in the static tester. This will soon be integrated into Travis.

### CODE REVIEW

**Comment by nedwill** [comment]
@tim-becker Code review?

**Comment by geohot** [comment]
So be careful with Python threads, they aren't preemptable. Each "chunk" of code will block until it finishes. I believe in the dynamic thread I have a sleep in the loop. Not saying this is the best solution, but verify each chunk can't take longer then say, 50ms.

**Comment by nedwill** [comment]
Oh, that's really interesting. I didn't understand the sleeps you had in those analysis functions until now. I can say that we are getting a bunch of getinstructions calls going over 50ms now so I'll take a look at that and make another commit.

**Comment by nedwill** [comment]
So some not so clever sleeps in make_function_at eliminated all the very long lag spikes (> 1 second) when waiting for large functions' CFGs. But we still have about twice as many >50ms delays with static on now. I bet I can play with it and get it back down to previous levels.

**Comment by geohot** [comment]
The idea of those sleeps pisses me off, but I don't really have a better idea. Python is effectively only one thread. An alternative is calling into the analysis routine from the event loop when it's idle. This is what IDA does.

**Comment by geohot** [comment]
Actually doesn't have to be this PR, but the event loop explicitly calling(scheduling) the dynamic analysis, file reader, and static is better, because then we can instrument it much better, and print a warning if 50ms(or some UI lag target) isn't being hit.

**Comment by nedwill** [comment]
Ok I committed the sleeps I added. I just moved them around until it seemed like the lag was reduced the most according to the socket warnings. Very unscientific. I think doing a refactor where we call out of the event loop would be really nice. If it's not too difficult we can get it in before v1.2. It'll help make sure we can hit the 50ms target more reliably, as I think perceived performance is critical. It's what makes it so useful pre-static - stepping around quickly without lag.

**Comment by nedwill** [comment]
Unfortunately it seems like there's still lag when we're in functions with large graphs. I wonder if there's a good way to address that. If it's not a frontend issue I can investigate that. Static release should be really snappy and it's worth putting more time into getting it.

**Comment by geohot** [comment]
Merged, since it's a strict improvement of what was there. I think the only way forward is static is always on though, and there's still work to be done.

One of these days I want to write a good suite of tests for the QIRA interface.

**Pull request merged**
