### PR TITLE
Tests Cleanup

### PR DESCRIPTION
**Pull request by nedwill**
This pull request cleans up the tests directory by moving all the source files that we can compile with no extra tinkering to the autogen folder and removing binaries for which we have source from the original tests folder. The C files that are deleted are ones that are actually present now in both the regular and autogen tests dir. Everything else changed should be just git mv's.

### CODE REVIEW

**Comment by geohot** [comment]
It's nice to see someone fixed travis.

With my new job, I don't have so much time to do the QIRA reviews anymore. Ideally you guys should start reviewing them in the group. How are things at CMU?

**Comment by nedwill** [comment]
Tim and I are still working on it during the semester and we have Ivan on the BAP side who seems receptive to QIRA's goals. Like you mentioned in the issue about academic code, we want to maintain QIRA's value to users, especially on the main branch. If I can't just clone it in a CTF and make use of it, it's not achieving its goal. That's why the fixes we've made recently had a focus on adding quality to the BAP changes and the static testing stuff. We don't want to merge bad/untested stuff (I learned this the hard way, and IMO BAP needs to be 100% for a release). We have some side branches involving a concrete executor/BAP experiments that we hope will let us add symbolic execution, but we'll make sure not to touch the main branch unless it's really high quality. And honestly, I may wait for your opinion on some more significant things down the line (symbolic execution) if they're not in line with your vision for QIRA or you find them implemented poorly. It is your project, after all.

As far as code reviews for the more incremental changes, I'll definitely keep an eye out for crappy pull requests. We already generally work together in person but going over them carefully should be worthwhile. I'll have someone else review my changes and vice versa. Good luck with your new job! I'll respond to the issues you opened and add some of my own soon so the project's direction is clearer from our end.

**Comment by geohot** [comment]
I don't want to discourage you from adding the symbolic stuff, and trunk BAP(just like trunk of anything else) doesn't have to be usable during a CTF. That's what 1.0 and releases are for, check out https://code.google.com/p/qira/wiki/shippingQIRAv1 if you want to see the milestones I needed to reach for 1.0

All I'm saying with the no academic code stuff is don't design for a paper, really either for QIRA or anything else. Design with the intent of production code, even if some stuff doesn't make production(check out how much stuff I added and removed from QIRA). If you want to add symbolic execution stuff, make a plan, mock it up, decide what's required, and do it.

**Comment by nedwill** [comment]
Thanks for the clarification. We'll definitely put an emphasis on production quality, especially for releases. And like you said, some stuff won't make the cut. The shipping QIRA v1 is really helpful though. We might fix a date to get another release out considering a lot has been done since v1.1, once things are ready, and I'll probably use a similar format to track the release plan. Then we can look to integrating symbolic exec. I remember you said QIRA's goal was to be a requirement for being competitive in CTF, and I think we can get there if we keep working on it. At least I find that possibility exciting.

-Ned

**Pull request merged**
