### PR TITLE
qira test fix depercated libicu48 & allow new distros to use newer …

### PR DESCRIPTION
**Pull request by Maroc-OS**
…phantomjs.

### CODE REVIEW

**Comment by nedwill** [comment]
Looks good, I'll merge once Travis finishes.

**Comment by Maroc-OS** [comment]
```
./install.sh: line 33: [: missing `]'

./install.sh: line 33: [a7bf1cb814c6e712a314659b074bc4c00d2e0006cac67d055d3130d4ecdd525d: command not found
```

now travis fail because of bad shecksum it was passing even if it's not a valid hash.

**Comment by nedwill** [comment]
Yikes really? I recall checking that bad checksums don't get through - maybe it's a different version of bash?

**Comment by nedwill** [comment]
Wait it looks like Travis was ok on the previous commit and it's broken now. Am I reading this right?

**Comment by Maroc-OS** [comment]
yes check out why i added infos to my old comment.

**Comment by Maroc-OS** [comment]
it was a silent bug.

**Comment by Maroc-OS** [comment]
maybe there is a way to checkup if it's the shell version or not ll add verbos to sha1 and see if it is okay

**Comment by nedwill** [comment]
No I figured out the problem, we should be using `&&` not `||` there.

**Comment by Maroc-OS** [comment]
Great. fix it then :)

**Comment by nedwill** [comment]
The problem was added in 7d069b597f5d7f88faa94add8534b9e95dec86b4. I need to be more careful with backdoor-installing contributions ;). And fixed in master.

**Comment by Maroc-OS** [comment]
:) yep :)

**Pull request merged**
